name: ShareIt API Tests

on:
  pull_request:

jobs:
  build:
    steps:
      - name: Clear cache
        run: rm -rf ${{ github.workspace }}/checkstyle.xml

      - name: Run API Tests
        uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci
